export const COUNTRIES = {
  AD: {
    countryCode: "AD",
    isoAlpha3: "AND",
    fipsCode: "AN",
    isoNumeric: 20,
    currencyCode: "EUR",
    languages: ["ca"],
    postalCodeFormat: "AD###",
    callingCode: "+376",
    timezones: ["Europe/Andorra"],
  },
  AE: {
    countryCode: "AE",
    isoAlpha3: "ARE",
    fipsCode: "AE",
    isoNumeric: 784,
    currencyCode: "AED",
    languages: ["ar-AE", "fa", "en", "hi", "ur"],
    postalCodeFormat: null,
    callingCode: "+971",
    timezones: ["Asia/Dubai"],
  },
  AF: {
    countryCode: "AF",
    isoAlpha3: "AFG",
    fipsCode: "AF",
    isoNumeric: 4,
    currencyCode: "AFN",
    languages: ["fa-AF", "ps", "uz-AF", "tk"],
    postalCodeFormat: null,
    callingCode: "+93",
    timezones: ["Asia/Kabul"],
  },
  AG: {
    countryCode: "AG",
    isoAlpha3: "ATG",
    fipsCode: "AC",
    isoNumeric: 28,
    currencyCode: "XCD",
    languages: ["en-AG"],
    postalCodeFormat: null,
    callingCode: "+1268",
    timezones: ["America/Antigua"],
  },
  AI: {
    countryCode: "AI",
    isoAlpha3: "AIA",
    fipsCode: "AV",
    isoNumeric: 660,
    currencyCode: "XCD",
    languages: ["en-AI"],
    postalCodeFormat: null,
    callingCode: "+1264",
    timezones: ["America/Anguilla"],
  },
  AL: {
    countryCode: "AL",
    isoAlpha3: "ALB",
    fipsCode: "AL",
    isoNumeric: 8,
    currencyCode: "ALL",
    languages: ["sq", "el"],
    postalCodeFormat: "####",
    callingCode: "+355",
    timezones: ["Europe/Tirane"],
  },
  AM: {
    countryCode: "AM",
    isoAlpha3: "ARM",
    fipsCode: "AM",
    isoNumeric: 51,
    currencyCode: "AMD",
    languages: ["hy"],
    postalCodeFormat: "######",
    callingCode: "+374",
    timezones: ["Asia/Yerevan"],
  },
  AO: {
    countryCode: "AO",
    isoAlpha3: "AGO",
    fipsCode: "AO",
    isoNumeric: 24,
    currencyCode: "AOA",
    languages: ["pt-AO"],
    postalCodeFormat: null,
    callingCode: "+244",
    timezones: ["Africa/Luanda"],
  },
  AQ: {
    countryCode: "AQ",
    isoAlpha3: "ATA",
    fipsCode: "AY",
    isoNumeric: 10,
    currencyCode: null,
    languages: [],
    postalCodeFormat: null,
    callingCode: "+672",
    timezones: [
      "Antarctica/McMurdo",
      "Antarctica/Casey",
      "Antarctica/Davis",
      "Antarctica/DumontDUrville",
      "Antarctica/Mawson",
      "Antarctica/Palmer",
      "Antarctica/Rothera",
      "Antarctica/Syowa",
      "Antarctica/Troll",
      "Antarctica/Vostok",
    ],
  },
  AR: {
    countryCode: "AR",
    isoAlpha3: "ARG",
    fipsCode: "AR",
    isoNumeric: 32,
    currencyCode: "ARS",
    languages: ["es-AR", "en", "it", "de", "fr", "gn"],
    postalCodeFormat: "@####@@@",
    callingCode: "+54",
    timezones: [
      "America/Argentina/Buenos_Aires",
      "America/Argentina/Cordoba",
      "America/Argentina/Salta",
      "America/Argentina/Jujuy",
      "America/Argentina/Tucuman",
      "America/Argentina/Catamarca",
      "America/Argentina/La_Rioja",
      "America/Argentina/San_Juan",
      "America/Argentina/Mendoza",
      "America/Argentina/San_Luis",
      "America/Argentina/Rio_Gallegos",
      "America/Argentina/Ushuaia",
    ],
  },
  AS: {
    countryCode: "AS",
    isoAlpha3: "ASM",
    fipsCode: "AQ",
    isoNumeric: 16,
    currencyCode: "USD",
    languages: ["en-AS", "sm", "to"],
    postalCodeFormat: "#####-####",
    callingCode: "+1684",
    timezones: ["Pacific/Pago_Pago"],
  },
  AT: {
    countryCode: "AT",
    isoAlpha3: "AUT",
    fipsCode: "AU",
    isoNumeric: 40,
    currencyCode: "EUR",
    languages: ["de-AT", "hr", "hu", "sl"],
    postalCodeFormat: "####",
    callingCode: "+43",
    timezones: ["Europe/Vienna"],
  },
  AU: {
    countryCode: "AU",
    isoAlpha3: "AUS",
    fipsCode: "AS",
    isoNumeric: 36,
    currencyCode: "AUD",
    languages: ["en-AU"],
    postalCodeFormat: "####",
    callingCode: "+61",
    timezones: [
      "Australia/Lord_Howe",
      "Antarctica/Macquarie",
      "Australia/Hobart",
      "Australia/Currie",
      "Australia/Melbourne",
      "Australia/Sydney",
      "Australia/Broken_Hill",
      "Australia/Brisbane",
      "Australia/Lindeman",
      "Australia/Adelaide",
      "Australia/Darwin",
      "Australia/Perth",
      "Australia/Eucla",
    ],
  },
  AW: {
    countryCode: "AW",
    isoAlpha3: "ABW",
    fipsCode: "AA",
    isoNumeric: 533,
    currencyCode: "AWG",
    languages: ["nl-AW", "pap", "es", "en"],
    postalCodeFormat: null,
    callingCode: "+297",
    timezones: ["America/Aruba"],
  },
  AX: {
    countryCode: "AX",
    isoAlpha3: "ALA",
    fipsCode: null,
    isoNumeric: 248,
    currencyCode: "EUR",
    languages: ["sv-AX"],
    postalCodeFormat: "#####",
    callingCode: "+358",
    timezones: ["Europe/Mariehamn"],
  },
  AZ: {
    countryCode: "AZ",
    isoAlpha3: "AZE",
    fipsCode: "AJ",
    isoNumeric: 31,
    currencyCode: "AZN",
    languages: ["az", "ru", "hy"],
    postalCodeFormat: "AZ ####",
    callingCode: "+994",
    timezones: ["Asia/Baku"],
  },
  BA: {
    countryCode: "BA",
    isoAlpha3: "BIH",
    fipsCode: "BK",
    isoNumeric: 70,
    currencyCode: "BAM",
    languages: ["bs", "hr-BA", "sr-BA"],
    postalCodeFormat: "#####",
    callingCode: "+387",
    timezones: ["Europe/Sarajevo"],
  },
  BB: {
    countryCode: "BB",
    isoAlpha3: "BRB",
    fipsCode: "BB",
    isoNumeric: 52,
    currencyCode: "BBD",
    languages: ["en-BB"],
    postalCodeFormat: "BB#####",
    callingCode: "+1246",
    timezones: ["America/Barbados"],
  },
  BD: {
    countryCode: "BD",
    isoAlpha3: "BGD",
    fipsCode: "BG",
    isoNumeric: 50,
    currencyCode: "BDT",
    languages: ["bn-BD", "en"],
    postalCodeFormat: "####",
    callingCode: "+880",
    timezones: ["Asia/Dhaka"],
  },
  BE: {
    countryCode: "BE",
    isoAlpha3: "BEL",
    fipsCode: "BE",
    isoNumeric: 56,
    currencyCode: "EUR",
    languages: ["nl-BE", "fr-BE", "de-BE"],
    postalCodeFormat: "####",
    callingCode: "+32",
    timezones: ["Europe/Brussels"],
  },
  BF: {
    countryCode: "BF",
    isoAlpha3: "BFA",
    fipsCode: "UV",
    isoNumeric: 854,
    currencyCode: "XOF",
    languages: ["fr-BF", "mos"],
    postalCodeFormat: null,
    callingCode: "+226",
    timezones: ["Africa/Ouagadougou"],
  },
  BG: {
    countryCode: "BG",
    isoAlpha3: "BGR",
    fipsCode: "BU",
    isoNumeric: 100,
    currencyCode: "BGN",
    languages: ["bg", "tr-BG", "rom"],
    postalCodeFormat: "####",
    callingCode: "+359",
    timezones: ["Europe/Sofia"],
  },
  BH: {
    countryCode: "BH",
    isoAlpha3: "BHR",
    fipsCode: "BA",
    isoNumeric: 48,
    currencyCode: "BHD",
    languages: ["ar-BH", "en", "fa", "ur"],
    postalCodeFormat: "####|###",
    callingCode: "+973",
    timezones: ["Asia/Bahrain"],
  },
  BI: {
    countryCode: "BI",
    isoAlpha3: "BDI",
    fipsCode: "BY",
    isoNumeric: 108,
    currencyCode: "BIF",
    languages: ["fr-BI", "rn"],
    postalCodeFormat: null,
    callingCode: "+257",
    timezones: ["Africa/Bujumbura"],
  },
  BJ: {
    countryCode: "BJ",
    isoAlpha3: "BEN",
    fipsCode: "BN",
    isoNumeric: 204,
    currencyCode: "XOF",
    languages: ["fr-BJ"],
    postalCodeFormat: null,
    callingCode: "+229",
    timezones: ["Africa/Porto-Novo"],
  },
  BL: {
    countryCode: "BL",
    isoAlpha3: "BLM",
    fipsCode: "TB",
    isoNumeric: 652,
    currencyCode: "EUR",
    languages: ["fr"],
    postalCodeFormat: "#####",
    callingCode: "+590",
    timezones: ["America/St_Barthelemy"],
  },
  BM: {
    countryCode: "BM",
    isoAlpha3: "BMU",
    fipsCode: "BD",
    isoNumeric: 60,
    currencyCode: "BMD",
    languages: ["en-BM", "pt"],
    postalCodeFormat: "@@ ##",
    callingCode: "+1441",
    timezones: ["Atlantic/Bermuda"],
  },
  BN: {
    countryCode: "BN",
    isoAlpha3: "BRN",
    fipsCode: "BX",
    isoNumeric: 96,
    currencyCode: "BND",
    languages: ["ms-BN", "en-BN"],
    postalCodeFormat: "@@####",
    callingCode: "+673",
    timezones: ["Asia/Brunei"],
  },
  BO: {
    countryCode: "BO",
    isoAlpha3: "BOL",
    fipsCode: "BL",
    isoNumeric: 68,
    currencyCode: "BOB",
    languages: ["es-BO", "qu", "ay"],
    postalCodeFormat: null,
    callingCode: "+591",
    timezones: ["America/La_Paz"],
  },
  BQ: {
    countryCode: "BQ",
    isoAlpha3: "BES",
    fipsCode: null,
    isoNumeric: 535,
    currencyCode: "USD",
    languages: ["nl", "pap", "en"],
    postalCodeFormat: null,
    callingCode: "+599",
    timezones: ["America/Kralendijk"],
  },
  BR: {
    countryCode: "BR",
    isoAlpha3: "BRA",
    fipsCode: "BR",
    isoNumeric: 76,
    currencyCode: "BRL",
    languages: ["pt-BR", "es", "en", "fr"],
    postalCodeFormat: "#####-###",
    callingCode: "+55",
    timezones: [
      "America/Noronha",
      "America/Belem",
      "America/Fortaleza",
      "America/Recife",
      "America/Araguaina",
      "America/Maceio",
      "America/Bahia",
      "America/Sao_Paulo",
      "America/Campo_Grande",
      "America/Cuiaba",
      "America/Santarem",
      "America/Porto_Velho",
      "America/Boa_Vista",
      "America/Manaus",
      "America/Eirunepe",
      "America/Rio_Branco",
    ],
  },
  BS: {
    countryCode: "BS",
    isoAlpha3: "BHS",
    fipsCode: "BF",
    isoNumeric: 44,
    currencyCode: "BSD",
    languages: ["en-BS"],
    postalCodeFormat: null,
    callingCode: "+1242",
    timezones: ["America/Nassau"],
  },
  BT: {
    countryCode: "BT",
    isoAlpha3: "BTN",
    fipsCode: "BT",
    isoNumeric: 64,
    currencyCode: "BTN",
    languages: ["dz"],
    postalCodeFormat: null,
    callingCode: "+975",
    timezones: ["Asia/Thimphu"],
  },
  BV: {
    countryCode: "BV",
    isoAlpha3: "BVT",
    fipsCode: "BV",
    isoNumeric: 74,
    currencyCode: "NOK",
    languages: [],
    postalCodeFormat: null,
    callingCode: "+55",
    timezones: ["Europe/Oslo"],
  },
  BW: {
    countryCode: "BW",
    isoAlpha3: "BWA",
    fipsCode: "BC",
    isoNumeric: 72,
    currencyCode: "BWP",
    languages: ["en-BW", "tn-BW"],
    postalCodeFormat: null,
    callingCode: "+267",
    timezones: ["Africa/Gaborone"],
  },
  BY: {
    countryCode: "BY",
    isoAlpha3: "BLR",
    fipsCode: "BO",
    isoNumeric: 112,
    currencyCode: "BYN",
    languages: ["be", "ru"],
    postalCodeFormat: "######",
    callingCode: "+375",
    timezones: ["Europe/Minsk"],
  },
  BZ: {
    countryCode: "BZ",
    isoAlpha3: "BLZ",
    fipsCode: "BH",
    isoNumeric: 84,
    currencyCode: "BZD",
    languages: ["en-BZ", "es"],
    postalCodeFormat: null,
    callingCode: "+501",
    timezones: ["America/Belize"],
  },
  CA: {
    countryCode: "CA",
    isoAlpha3: "CAN",
    fipsCode: "CA",
    isoNumeric: 124,
    currencyCode: "CAD",
    languages: ["en-CA", "fr-CA", "iu"],
    postalCodeFormat: "@#@ #@#",
    callingCode: "+1",
    timezones: [
      "America/St_Johns",
      "America/Halifax",
      "America/Glace_Bay",
      "America/Moncton",
      "America/Goose_Bay",
      "America/Blanc-Sablon",
      "America/Toronto",
      "America/Nipigon",
      "America/Thunder_Bay",
      "America/Iqaluit",
      "America/Pangnirtung",
      "America/Atikokan",
      "America/Winnipeg",
      "America/Rainy_River",
      "America/Resolute",
      "America/Rankin_Inlet",
      "America/Regina",
      "America/Swift_Current",
      "America/Edmonton",
      "America/Cambridge_Bay",
      "America/Yellowknife",
      "America/Inuvik",
      "America/Creston",
      "America/Dawson_Creek",
      "America/Fort_Nelson",
      "America/Vancouver",
      "America/Whitehorse",
      "America/Dawson",
    ],
  },
  CC: {
    countryCode: "CC",
    isoAlpha3: "CCK",
    fipsCode: "CK",
    isoNumeric: 166,
    currencyCode: "AUD",
    languages: ["ms-CC", "en"],
    postalCodeFormat: null,
    callingCode: "+61",
    timezones: ["Indian/Cocos"],
  },
  CD: {
    countryCode: "CD",
    isoAlpha3: "COD",
    fipsCode: "CG",
    isoNumeric: 180,
    currencyCode: "CDF",
    languages: ["fr-CD", "ln", "ktu", "kg", "sw", "lua"],
    postalCodeFormat: null,
    callingCode: "+243",
    timezones: ["Africa/Kinshasa", "Africa/Lubumbashi"],
  },
  CF: {
    countryCode: "CF",
    isoAlpha3: "CAF",
    fipsCode: "CT",
    isoNumeric: 140,
    currencyCode: "XAF",
    languages: ["fr-CF", "sg", "ln", "kg"],
    postalCodeFormat: null,
    callingCode: "+236",
    timezones: ["Africa/Bangui"],
  },
  CG: {
    countryCode: "CG",
    isoAlpha3: "COG",
    fipsCode: "CF",
    isoNumeric: 178,
    currencyCode: "XAF",
    languages: ["fr-CG", "kg", "ln-CG"],
    postalCodeFormat: null,
    callingCode: "+242",
    timezones: ["Africa/Brazzaville"],
  },
  CH: {
    countryCode: "CH",
    isoAlpha3: "CHE",
    fipsCode: "SZ",
    isoNumeric: 756,
    currencyCode: "CHF",
    languages: ["de-CH", "fr-CH", "it-CH", "rm"],
    postalCodeFormat: "####",
    callingCode: "+41",
    timezones: ["Europe/Zurich"],
  },
  CI: {
    countryCode: "CI",
    isoAlpha3: "CIV",
    fipsCode: "IV",
    isoNumeric: 384,
    currencyCode: "XOF",
    languages: ["fr-CI"],
    postalCodeFormat: null,
    callingCode: "+225",
    timezones: ["Africa/Abidjan"],
  },
  CK: {
    countryCode: "CK",
    isoAlpha3: "COK",
    fipsCode: "CW",
    isoNumeric: 184,
    currencyCode: "NZD",
    languages: ["en-CK", "mi"],
    postalCodeFormat: null,
    callingCode: "+682",
    timezones: ["Pacific/Rarotonga"],
  },
  CL: {
    countryCode: "CL",
    isoAlpha3: "CHL",
    fipsCode: "CI",
    isoNumeric: 152,
    currencyCode: "CLP",
    languages: ["es-CL"],
    postalCodeFormat: "#######",
    callingCode: "+56",
    timezones: ["America/Santiago", "Pacific/Easter"],
  },
  CM: {
    countryCode: "CM",
    isoAlpha3: "CMR",
    fipsCode: "CM",
    isoNumeric: 120,
    currencyCode: "XAF",
    languages: ["en-CM", "fr-CM"],
    postalCodeFormat: null,
    callingCode: "+237",
    timezones: ["Africa/Douala"],
  },
  CN: {
    countryCode: "CN",
    isoAlpha3: "CHN",
    fipsCode: "CH",
    isoNumeric: 156,
    currencyCode: "CNY",
    languages: ["zh-CN", "yue", "wuu", "dta", "ug", "za"],
    postalCodeFormat: "######",
    callingCode: "+86",
    timezones: ["Asia/Shanghai", "Asia/Urumqi"],
  },
  CO: {
    countryCode: "CO",
    isoAlpha3: "COL",
    fipsCode: "CO",
    isoNumeric: 170,
    currencyCode: "COP",
    languages: ["es-CO"],
    postalCodeFormat: "######",
    callingCode: "+57",
    timezones: ["America/Bogota"],
  },
  CR: {
    countryCode: "CR",
    isoAlpha3: "CRI",
    fipsCode: "CS",
    isoNumeric: 188,
    currencyCode: "CRC",
    languages: ["es-CR", "en"],
    postalCodeFormat: "#####",
    callingCode: "+506",
    timezones: ["America/Costa_Rica"],
  },
  CU: {
    countryCode: "CU",
    isoAlpha3: "CUB",
    fipsCode: "CU",
    isoNumeric: 192,
    currencyCode: "CUP",
    languages: ["es-CU", "pap"],
    postalCodeFormat: "CP #####",
    callingCode: "+53",
    timezones: ["America/Havana"],
  },
  CV: {
    countryCode: "CV",
    isoAlpha3: "CPV",
    fipsCode: "CV",
    isoNumeric: 132,
    currencyCode: "CVE",
    languages: ["pt-CV"],
    postalCodeFormat: "####",
    callingCode: "+238",
    timezones: ["Atlantic/Cape_Verde"],
  },
  CW: {
    countryCode: "CW",
    isoAlpha3: "CUW",
    fipsCode: "UC",
    isoNumeric: 531,
    currencyCode: "ANG",
    languages: ["nl", "pap"],
    postalCodeFormat: null,
    callingCode: "+599",
    timezones: ["America/Curacao"],
  },
  CX: {
    countryCode: "CX",
    isoAlpha3: "CXR",
    fipsCode: "KT",
    isoNumeric: 162,
    currencyCode: "AUD",
    languages: ["en", "zh", "ms-CC"],
    postalCodeFormat: "####",
    callingCode: "+61",
    timezones: ["Indian/Christmas"],
  },
  CY: {
    countryCode: "CY",
    isoAlpha3: "CYP",
    fipsCode: "CY",
    isoNumeric: 196,
    currencyCode: "EUR",
    languages: ["el-CY", "tr-CY", "en"],
    postalCodeFormat: "####",
    callingCode: "+357",
    timezones: ["Asia/Nicosia"],
  },
  CZ: {
    countryCode: "CZ",
    isoAlpha3: "CZE",
    fipsCode: "EZ",
    isoNumeric: 203,
    currencyCode: "CZK",
    languages: ["cs", "sk"],
    postalCodeFormat: "### ##",
    callingCode: "+420",
    timezones: ["Europe/Prague"],
  },
  DE: {
    countryCode: "DE",
    isoAlpha3: "DEU",
    fipsCode: "GM",
    isoNumeric: 276,
    currencyCode: "EUR",
    languages: ["de"],
    postalCodeFormat: "#####",
    callingCode: "+49",
    timezones: ["Europe/Berlin", "Europe/Busingen"],
  },
  DJ: {
    countryCode: "DJ",
    isoAlpha3: "DJI",
    fipsCode: "DJ",
    isoNumeric: 262,
    currencyCode: "DJF",
    languages: ["fr-DJ", "ar", "so-DJ", "aa"],
    postalCodeFormat: null,
    callingCode: "+253",
    timezones: ["Africa/Djibouti"],
  },
  DK: {
    countryCode: "DK",
    isoAlpha3: "DNK",
    fipsCode: "DA",
    isoNumeric: 208,
    currencyCode: "DKK",
    languages: ["da-DK", "en", "fo", "de-DK"],
    postalCodeFormat: "####",
    callingCode: "+45",
    timezones: ["Europe/Copenhagen"],
  },
  DM: {
    countryCode: "DM",
    isoAlpha3: "DMA",
    fipsCode: "DO",
    isoNumeric: 212,
    currencyCode: "XCD",
    languages: ["en-DM"],
    postalCodeFormat: null,
    callingCode: "+1767",
    timezones: ["America/Dominica"],
  },
  DO: {
    countryCode: "DO",
    isoAlpha3: "DOM",
    fipsCode: "DR",
    isoNumeric: 214,
    currencyCode: "DOP",
    languages: ["es-DO"],
    postalCodeFormat: "#####",
    callingCode: "+1849",
    timezones: ["America/Santo_Domingo"],
  },
  DZ: {
    countryCode: "DZ",
    isoAlpha3: "DZA",
    fipsCode: "AG",
    isoNumeric: 12,
    currencyCode: "DZD",
    languages: ["ar-DZ"],
    postalCodeFormat: "#####",
    callingCode: "+213",
    timezones: ["Africa/Algiers"],
  },
  EC: {
    countryCode: "EC",
    isoAlpha3: "ECU",
    fipsCode: "EC",
    isoNumeric: 218,
    currencyCode: "USD",
    languages: ["es-EC"],
    postalCodeFormat: "@####@",
    callingCode: "+593",
    timezones: ["America/Guayaquil", "Pacific/Galapagos"],
  },
  EE: {
    countryCode: "EE",
    isoAlpha3: "EST",
    fipsCode: "EN",
    isoNumeric: 233,
    currencyCode: "EUR",
    languages: ["et", "ru"],
    postalCodeFormat: "#####",
    callingCode: "+372",
    timezones: ["Europe/Tallinn"],
  },
  EG: {
    countryCode: "EG",
    isoAlpha3: "EGY",
    fipsCode: "EG",
    isoNumeric: 818,
    currencyCode: "EGP",
    languages: ["ar-EG", "en", "fr"],
    postalCodeFormat: "#####",
    callingCode: "+20",
    timezones: ["Africa/Cairo"],
  },
  EH: {
    countryCode: "EH",
    isoAlpha3: "ESH",
    fipsCode: "WI",
    isoNumeric: 732,
    currencyCode: "MAD",
    languages: ["ar", "mey"],
    postalCodeFormat: null,
    callingCode: "+212",
    timezones: ["Africa/El_Aaiun"],
  },
  ER: {
    countryCode: "ER",
    isoAlpha3: "ERI",
    fipsCode: "ER",
    isoNumeric: 232,
    currencyCode: "ERN",
    languages: ["aa-ER", "ar", "tig", "kun", "ti-ER"],
    postalCodeFormat: null,
    callingCode: "+291",
    timezones: ["Africa/Asmara"],
  },
  ES: {
    countryCode: "ES",
    isoAlpha3: "ESP",
    fipsCode: "SP",
    isoNumeric: 724,
    currencyCode: "EUR",
    languages: ["es-ES", "ca", "gl", "eu", "oc"],
    postalCodeFormat: "#####",
    callingCode: "+34",
    timezones: ["Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"],
  },
  ET: {
    countryCode: "ET",
    isoAlpha3: "ETH",
    fipsCode: "ET",
    isoNumeric: 231,
    currencyCode: "ETB",
    languages: ["am", "en-ET", "om-ET", "ti-ET", "so-ET", "sid"],
    postalCodeFormat: "####",
    callingCode: "+251",
    timezones: ["Africa/Addis_Ababa"],
  },
  FI: {
    countryCode: "FI",
    isoAlpha3: "FIN",
    fipsCode: "FI",
    isoNumeric: 246,
    currencyCode: "EUR",
    languages: ["fi-FI", "sv-FI", "smn"],
    postalCodeFormat: "#####",
    callingCode: "+358",
    timezones: ["Europe/Helsinki"],
  },
  FJ: {
    countryCode: "FJ",
    isoAlpha3: "FJI",
    fipsCode: "FJ",
    isoNumeric: 242,
    currencyCode: "FJD",
    languages: ["en-FJ", "fj"],
    postalCodeFormat: null,
    callingCode: "+679",
    timezones: ["Pacific/Fiji"],
  },
  FK: {
    countryCode: "FK",
    isoAlpha3: "FLK",
    fipsCode: "FK",
    isoNumeric: 238,
    currencyCode: "FKP",
    languages: ["en-FK"],
    postalCodeFormat: null,
    callingCode: "+500",
    timezones: ["Atlantic/Stanley"],
  },
  FM: {
    countryCode: "FM",
    isoAlpha3: "FSM",
    fipsCode: "FM",
    isoNumeric: 583,
    currencyCode: "USD",
    languages: [
      "en-FM",
      "chk",
      "pon",
      "yap",
      "kos",
      "uli",
      "woe",
      "nkr",
      "kpg",
    ],
    postalCodeFormat: "#####",
    callingCode: "+691",
    timezones: ["Pacific/Chuuk", "Pacific/Pohnpei", "Pacific/Kosrae"],
  },
  FO: {
    countryCode: "FO",
    isoAlpha3: "FRO",
    fipsCode: "FO",
    isoNumeric: 234,
    currencyCode: "DKK",
    languages: ["fo", "da-FO"],
    postalCodeFormat: "###",
    callingCode: "+298",
    timezones: ["Atlantic/Faroe"],
  },
  FR: {
    countryCode: "FR",
    isoAlpha3: "FRA",
    fipsCode: "FR",
    isoNumeric: 250,
    currencyCode: "EUR",
    languages: ["fr-FR", "frp", "br", "co", "ca", "eu", "oc"],
    postalCodeFormat: "#####",
    callingCode: "+33",
    timezones: ["Europe/Paris"],
  },
  GA: {
    countryCode: "GA",
    isoAlpha3: "GAB",
    fipsCode: "GB",
    isoNumeric: 266,
    currencyCode: "XAF",
    languages: ["fr-GA"],
    postalCodeFormat: null,
    callingCode: "+241",
    timezones: ["Africa/Libreville"],
  },
  GB: {
    countryCode: "GB",
    isoAlpha3: "GBR",
    fipsCode: "UK",
    isoNumeric: 826,
    currencyCode: "GBP",
    languages: ["en-GB", "cy-GB", "gd"],
    postalCodeFormat: "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
    callingCode: "+44",
    timezones: ["Europe/London"],
  },
  GD: {
    countryCode: "GD",
    isoAlpha3: "GRD",
    fipsCode: "GJ",
    isoNumeric: 308,
    currencyCode: "XCD",
    languages: ["en-GD"],
    postalCodeFormat: null,
    callingCode: "+1473",
    timezones: ["America/Grenada"],
  },
  GE: {
    countryCode: "GE",
    isoAlpha3: "GEO",
    fipsCode: "GG",
    isoNumeric: 268,
    currencyCode: "GEL",
    languages: ["ka", "ru", "hy", "az"],
    postalCodeFormat: "####",
    callingCode: "+995",
    timezones: ["Asia/Tbilisi"],
  },
  GF: {
    countryCode: "GF",
    isoAlpha3: "GUF",
    fipsCode: "FG",
    isoNumeric: 254,
    currencyCode: "EUR",
    languages: ["fr-GF"],
    postalCodeFormat: "#####",
    callingCode: "+594",
    timezones: ["America/Cayenne"],
  },
  GG: {
    countryCode: "GG",
    isoAlpha3: "GGY",
    fipsCode: "GK",
    isoNumeric: 831,
    currencyCode: "GBP",
    languages: ["en", "nrf"],
    postalCodeFormat: "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
    callingCode: "+44",
    timezones: ["Europe/Guernsey"],
  },
  GH: {
    countryCode: "GH",
    isoAlpha3: "GHA",
    fipsCode: "GH",
    isoNumeric: 288,
    currencyCode: "GHS",
    languages: ["en-GH", "ak", "ee", "tw"],
    postalCodeFormat: null,
    callingCode: "+233",
    timezones: ["Africa/Accra"],
  },
  GI: {
    countryCode: "GI",
    isoAlpha3: "GIB",
    fipsCode: "GI",
    isoNumeric: 292,
    currencyCode: "GIP",
    languages: ["en-GI", "es", "it", "pt"],
    postalCodeFormat: null,
    callingCode: "+350",
    timezones: ["Europe/Gibraltar"],
  },
  GL: {
    countryCode: "GL",
    isoAlpha3: "GRL",
    fipsCode: "GL",
    isoNumeric: 304,
    currencyCode: "DKK",
    languages: ["kl", "da-GL", "en"],
    postalCodeFormat: "####",
    callingCode: "+299",
    timezones: [
      "America/Godthab",
      "America/Danmarkshavn",
      "America/Scoresbysund",
      "America/Thule",
    ],
  },
  GM: {
    countryCode: "GM",
    isoAlpha3: "GMB",
    fipsCode: "GA",
    isoNumeric: 270,
    currencyCode: "GMD",
    languages: ["en-GM", "mnk", "wof", "wo", "ff"],
    postalCodeFormat: null,
    callingCode: "+220",
    timezones: ["Africa/Banjul"],
  },
  GN: {
    countryCode: "GN",
    isoAlpha3: "GIN",
    fipsCode: "GV",
    isoNumeric: 324,
    currencyCode: "GNF",
    languages: ["fr-GN"],
    postalCodeFormat: null,
    callingCode: "+224",
    timezones: ["Africa/Conakry"],
  },
  GP: {
    countryCode: "GP",
    isoAlpha3: "GLP",
    fipsCode: "GP",
    isoNumeric: 312,
    currencyCode: "EUR",
    languages: ["fr-GP"],
    postalCodeFormat: "#####",
    callingCode: "+590",
    timezones: ["America/Guadeloupe"],
  },
  GQ: {
    countryCode: "GQ",
    isoAlpha3: "GNQ",
    fipsCode: "EK",
    isoNumeric: 226,
    currencyCode: "XAF",
    languages: ["es-GQ", "fr", "pt"],
    postalCodeFormat: null,
    callingCode: "+240",
    timezones: ["Africa/Malabo"],
  },
  GR: {
    countryCode: "GR",
    isoAlpha3: "GRC",
    fipsCode: "GR",
    isoNumeric: 300,
    currencyCode: "EUR",
    languages: ["el-GR", "en", "fr"],
    postalCodeFormat: "### ##",
    callingCode: "+30",
    timezones: ["Europe/Athens"],
  },
  GS: {
    countryCode: "GS",
    isoAlpha3: "SGS",
    fipsCode: "SX",
    isoNumeric: 239,
    currencyCode: "GBP",
    languages: ["en"],
    postalCodeFormat: null,
    callingCode: "+500",
    timezones: ["Atlantic/South_Georgia"],
  },
  GT: {
    countryCode: "GT",
    isoAlpha3: "GTM",
    fipsCode: "GT",
    isoNumeric: 320,
    currencyCode: "GTQ",
    languages: ["es-GT"],
    postalCodeFormat: "#####",
    callingCode: "+502",
    timezones: ["America/Guatemala"],
  },
  GU: {
    countryCode: "GU",
    isoAlpha3: "GUM",
    fipsCode: "GQ",
    isoNumeric: 316,
    currencyCode: "USD",
    languages: ["en-GU", "ch-GU"],
    postalCodeFormat: "969##",
    callingCode: "+1671",
    timezones: ["Pacific/Guam"],
  },
  GW: {
    countryCode: "GW",
    isoAlpha3: "GNB",
    fipsCode: "PU",
    isoNumeric: 624,
    currencyCode: "XOF",
    languages: ["pt-GW", "pov"],
    postalCodeFormat: "####",
    callingCode: "+245",
    timezones: ["Africa/Bissau"],
  },
  GY: {
    countryCode: "GY",
    isoAlpha3: "GUY",
    fipsCode: "GY",
    isoNumeric: 328,
    currencyCode: "GYD",
    languages: ["en-GY"],
    postalCodeFormat: null,
    callingCode: "+595",
    timezones: ["America/Guyana"],
  },
  HK: {
    countryCode: "HK",
    isoAlpha3: "HKG",
    fipsCode: "HK",
    isoNumeric: 344,
    currencyCode: "HKD",
    languages: ["zh-HK", "yue", "zh", "en"],
    postalCodeFormat: null,
    callingCode: "+852",
    timezones: ["Asia/Hong_Kong"],
  },
  HM: {
    countryCode: "HM",
    isoAlpha3: "HMD",
    fipsCode: "HM",
    isoNumeric: 334,
    currencyCode: "AUD",
    languages: [],
    postalCodeFormat: null,
    callingCode: "+672",
    timezones: ["Etc/GMT-5"],
  },
  HN: {
    countryCode: "HN",
    isoAlpha3: "HND",
    fipsCode: "HO",
    isoNumeric: 340,
    currencyCode: "HNL",
    languages: ["es-HN", "cab", "miq"],
    postalCodeFormat: "@@####",
    callingCode: "+504",
    timezones: ["America/Tegucigalpa"],
  },
  HR: {
    countryCode: "HR",
    isoAlpha3: "HRV",
    fipsCode: "HR",
    isoNumeric: 191,
    currencyCode: "HRK",
    languages: ["hr-HR", "sr"],
    postalCodeFormat: "#####",
    callingCode: "+385",
    timezones: ["Europe/Zagreb"],
  },
  HT: {
    countryCode: "HT",
    isoAlpha3: "HTI",
    fipsCode: "HA",
    isoNumeric: 332,
    currencyCode: "HTG",
    languages: ["ht", "fr-HT"],
    postalCodeFormat: "HT####",
    callingCode: "+509",
    timezones: ["America/Port-au-Prince"],
  },
  HU: {
    countryCode: "HU",
    isoAlpha3: "HUN",
    fipsCode: "HU",
    isoNumeric: 348,
    currencyCode: "HUF",
    languages: ["hu-HU"],
    postalCodeFormat: "####",
    callingCode: "+36",
    timezones: ["Europe/Budapest"],
  },
  ID: {
    countryCode: "ID",
    isoAlpha3: "IDN",
    fipsCode: "ID",
    isoNumeric: 360,
    currencyCode: "IDR",
    languages: ["id", "en", "nl", "jv"],
    postalCodeFormat: "#####",
    callingCode: "+62",
    timezones: [
      "Asia/Jakarta",
      "Asia/Pontianak",
      "Asia/Makassar",
      "Asia/Jayapura",
    ],
  },
  IE: {
    countryCode: "IE",
    isoAlpha3: "IRL",
    fipsCode: "EI",
    isoNumeric: 372,
    currencyCode: "EUR",
    languages: ["en-IE", "ga-IE"],
    postalCodeFormat: "@@@ @@@@",
    callingCode: "+353",
    timezones: ["Europe/Dublin"],
  },
  IL: {
    countryCode: "IL",
    isoAlpha3: "ISR",
    fipsCode: "IS",
    isoNumeric: 376,
    currencyCode: "ILS",
    languages: ["he", "ar-IL", "en-IL"],
    postalCodeFormat: "#######",
    callingCode: "+972",
    timezones: ["Asia/Jerusalem"],
  },
  IM: {
    countryCode: "IM",
    isoAlpha3: "IMN",
    fipsCode: "IM",
    isoNumeric: 833,
    currencyCode: "GBP",
    languages: ["en", "gv"],
    postalCodeFormat: "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
    callingCode: "+44",
    timezones: ["Europe/Isle_of_Man"],
  },
  IN: {
    countryCode: "IN",
    isoAlpha3: "IND",
    fipsCode: "IN",
    isoNumeric: 356,
    currencyCode: "INR",
    languages: [
      "en-IN",
      "hi",
      "bn",
      "te",
      "mr",
      "ta",
      "ur",
      "gu",
      "kn",
      "ml",
      "or",
      "pa",
      "as",
      "bh",
      "sat",
      "ks",
      "ne",
      "sd",
      "kok",
      "doi",
      "mni",
      "sit",
      "sa",
      "fr",
      "lus",
      "inc",
    ],
    postalCodeFormat: "######",
    callingCode: "+91",
    timezones: ["Asia/Kolkata"],
  },
  IO: {
    countryCode: "IO",
    isoAlpha3: "IOT",
    fipsCode: "IO",
    isoNumeric: 86,
    currencyCode: "USD",
    languages: ["en-IO"],
    postalCodeFormat: null,
    callingCode: "+246",
    timezones: ["Indian/Chagos"],
  },
  IQ: {
    countryCode: "IQ",
    isoAlpha3: "IRQ",
    fipsCode: "IZ",
    isoNumeric: 368,
    currencyCode: "IQD",
    languages: ["ar-IQ", "ku", "hy"],
    postalCodeFormat: "#####",
    callingCode: "+964",
    timezones: ["Asia/Baghdad"],
  },
  IR: {
    countryCode: "IR",
    isoAlpha3: "IRN",
    fipsCode: "IR",
    isoNumeric: 364,
    currencyCode: "IRR",
    languages: ["fa-IR", "ku"],
    postalCodeFormat: "##########",
    callingCode: "+98",
    timezones: ["Asia/Tehran"],
  },
  IS: {
    countryCode: "IS",
    isoAlpha3: "ISL",
    fipsCode: "IC",
    isoNumeric: 352,
    currencyCode: "ISK",
    languages: ["is", "en", "de", "da", "sv", "no"],
    postalCodeFormat: "###",
    callingCode: "+354",
    timezones: ["Atlantic/Reykjavik"],
  },
  IT: {
    countryCode: "IT",
    isoAlpha3: "ITA",
    fipsCode: "IT",
    isoNumeric: 380,
    currencyCode: "EUR",
    languages: ["it-IT", "de-IT", "fr-IT", "sc", "ca", "co", "sl"],
    postalCodeFormat: "#####",
    callingCode: "+39",
    timezones: ["Europe/Rome"],
  },
  JE: {
    countryCode: "JE",
    isoAlpha3: "JEY",
    fipsCode: "JE",
    isoNumeric: 832,
    currencyCode: "GBP",
    languages: ["en", "fr", "nrf"],
    postalCodeFormat: "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA",
    callingCode: "+44",
    timezones: ["Europe/Jersey"],
  },
  JM: {
    countryCode: "JM",
    isoAlpha3: "JAM",
    fipsCode: "JM",
    isoNumeric: 388,
    currencyCode: "JMD",
    languages: ["en-JM"],
    postalCodeFormat: null,
    callingCode: "+1876",
    timezones: ["America/Jamaica"],
  },
  JO: {
    countryCode: "JO",
    isoAlpha3: "JOR",
    fipsCode: "JO",
    isoNumeric: 400,
    currencyCode: "JOD",
    languages: ["ar-JO", "en"],
    postalCodeFormat: "#####",
    callingCode: "+962",
    timezones: ["Asia/Amman"],
  },
  JP: {
    countryCode: "JP",
    isoAlpha3: "JPN",
    fipsCode: "JA",
    isoNumeric: 392,
    currencyCode: "JPY",
    languages: ["ja"],
    postalCodeFormat: "###-####",
    callingCode: "+81",
    timezones: ["Asia/Tokyo"],
  },
  KE: {
    countryCode: "KE",
    isoAlpha3: "KEN",
    fipsCode: "KE",
    isoNumeric: 404,
    currencyCode: "KES",
    languages: ["en-KE", "sw-KE"],
    postalCodeFormat: "#####",
    callingCode: "+254",
    timezones: ["Africa/Nairobi"],
  },
  KG: {
    countryCode: "KG",
    isoAlpha3: "KGZ",
    fipsCode: "KG",
    isoNumeric: 417,
    currencyCode: "KGS",
    languages: ["ky", "uz", "ru"],
    postalCodeFormat: "######",
    callingCode: "+996",
    timezones: ["Asia/Bishkek"],
  },
  KH: {
    countryCode: "KH",
    isoAlpha3: "KHM",
    fipsCode: "CB",
    isoNumeric: 116,
    currencyCode: "KHR",
    languages: ["km", "fr", "en"],
    postalCodeFormat: "#####",
    callingCode: "+855",
    timezones: ["Asia/Phnom_Penh"],
  },
  KI: {
    countryCode: "KI",
    isoAlpha3: "KIR",
    fipsCode: "KR",
    isoNumeric: 296,
    currencyCode: "AUD",
    languages: ["en-KI", "gil"],
    postalCodeFormat: null,
    callingCode: "+686",
    timezones: ["Pacific/Tarawa", "Pacific/Enderbury", "Pacific/Kiritimati"],
  },
  KM: {
    countryCode: "KM",
    isoAlpha3: "COM",
    fipsCode: "CN",
    isoNumeric: 174,
    currencyCode: "KMF",
    languages: ["ar", "fr-KM"],
    postalCodeFormat: null,
    callingCode: "+269",
    timezones: ["Indian/Comoro"],
  },
  KN: {
    countryCode: "KN",
    isoAlpha3: "KNA",
    fipsCode: "SC",
    isoNumeric: 659,
    currencyCode: "XCD",
    languages: ["en-KN"],
    postalCodeFormat: null,
    callingCode: "+1869",
    timezones: ["America/St_Kitts"],
  },
  KP: {
    countryCode: "KP",
    isoAlpha3: "PRK",
    fipsCode: "KN",
    isoNumeric: 408,
    currencyCode: "KPW",
    languages: ["ko-KP"],
    postalCodeFormat: "###-###",
    callingCode: "+850",
    timezones: ["Asia/Pyongyang"],
  },
  KR: {
    countryCode: "KR",
    isoAlpha3: "KOR",
    fipsCode: "KS",
    isoNumeric: 410,
    currencyCode: "KRW",
    languages: ["ko-KR", "en"],
    postalCodeFormat: "#####",
    callingCode: "+82",
    timezones: ["Asia/Seoul"],
  },
  KW: {
    countryCode: "KW",
    isoAlpha3: "KWT",
    fipsCode: "KU",
    isoNumeric: 414,
    currencyCode: "KWD",
    languages: ["ar-KW", "en"],
    postalCodeFormat: "#####",
    callingCode: "+965",
    timezones: ["Asia/Kuwait"],
  },
  KY: {
    countryCode: "KY",
    isoAlpha3: "CYM",
    fipsCode: "CJ",
    isoNumeric: 136,
    currencyCode: "KYD",
    languages: ["en-KY"],
    postalCodeFormat: null,
    callingCode: "+345",
    timezones: ["America/Cayman"],
  },
  KZ: {
    countryCode: "KZ",
    isoAlpha3: "KAZ",
    fipsCode: "KZ",
    isoNumeric: 398,
    currencyCode: "KZT",
    languages: ["kk", "ru"],
    postalCodeFormat: "######",
    callingCode: "+77",
    timezones: [
      "Asia/Almaty",
      "Asia/Qyzylorda",
      "Asia/Aqtobe",
      "Asia/Aqtau",
      "Asia/Oral",
    ],
  },
  LA: {
    countryCode: "LA",
    isoAlpha3: "LAO",
    fipsCode: "LA",
    isoNumeric: 418,
    currencyCode: "LAK",
    languages: ["lo", "fr", "en"],
    postalCodeFormat: "#####",
    callingCode: "+856",
    timezones: ["Asia/Vientiane"],
  },
  LB: {
    countryCode: "LB",
    isoAlpha3: "LBN",
    fipsCode: "LE",
    isoNumeric: 422,
    currencyCode: "LBP",
    languages: ["ar-LB", "fr-LB", "en", "hy"],
    postalCodeFormat: "#### ####|####",
    callingCode: "+961",
    timezones: ["Asia/Beirut"],
  },
  LC: {
    countryCode: "LC",
    isoAlpha3: "LCA",
    fipsCode: "ST",
    isoNumeric: 662,
    currencyCode: "XCD",
    languages: ["en-LC"],
    postalCodeFormat: null,
    callingCode: "+1758",
    timezones: ["America/St_Lucia"],
  },
  LI: {
    countryCode: "LI",
    isoAlpha3: "LIE",
    fipsCode: "LS",
    isoNumeric: 438,
    currencyCode: "CHF",
    languages: ["de-LI"],
    postalCodeFormat: "####",
    callingCode: "+423",
    timezones: ["Europe/Vaduz"],
  },
  LK: {
    countryCode: "LK",
    isoAlpha3: "LKA",
    fipsCode: "CE",
    isoNumeric: 144,
    currencyCode: "LKR",
    languages: ["si", "ta", "en"],
    postalCodeFormat: "#####",
    callingCode: "+94",
    timezones: ["Asia/Colombo"],
  },
  LR: {
    countryCode: "LR",
    isoAlpha3: "LBR",
    fipsCode: "LI",
    isoNumeric: 430,
    currencyCode: "LRD",
    languages: ["en-LR"],
    postalCodeFormat: "####",
    callingCode: "+231",
    timezones: ["Africa/Monrovia"],
  },
  LS: {
    countryCode: "LS",
    isoAlpha3: "LSO",
    fipsCode: "LT",
    isoNumeric: 426,
    currencyCode: "LSL",
    languages: ["en-LS", "st", "zu", "xh"],
    postalCodeFormat: "###",
    callingCode: "+266",
    timezones: ["Africa/Maseru"],
  },
  LT: {
    countryCode: "LT",
    isoAlpha3: "LTU",
    fipsCode: "LH",
    isoNumeric: 440,
    currencyCode: "EUR",
    languages: ["lt", "ru", "pl"],
    postalCodeFormat: "LT-#####",
    callingCode: "+370",
    timezones: ["Europe/Vilnius"],
  },
  LU: {
    countryCode: "LU",
    isoAlpha3: "LUX",
    fipsCode: "LU",
    isoNumeric: 442,
    currencyCode: "EUR",
    languages: ["lb", "de-LU", "fr-LU"],
    postalCodeFormat: "L-####",
    callingCode: "+352",
    timezones: ["Europe/Luxembourg"],
  },
  LV: {
    countryCode: "LV",
    isoAlpha3: "LVA",
    fipsCode: "LG",
    isoNumeric: 428,
    currencyCode: "EUR",
    languages: ["lv", "ru", "lt"],
    postalCodeFormat: "LV-####",
    callingCode: "+371",
    timezones: ["Europe/Riga"],
  },
  LY: {
    countryCode: "LY",
    isoAlpha3: "LBY",
    fipsCode: "LY",
    isoNumeric: 434,
    currencyCode: "LYD",
    languages: ["ar-LY", "it", "en"],
    postalCodeFormat: null,
    callingCode: "+218",
    timezones: ["Africa/Tripoli"],
  },
  MA: {
    countryCode: "MA",
    isoAlpha3: "MAR",
    fipsCode: "MO",
    isoNumeric: 504,
    currencyCode: "MAD",
    languages: ["ar-MA", "ber", "fr"],
    postalCodeFormat: "#####",
    callingCode: "+212",
    timezones: ["Africa/Casablanca"],
  },
  MC: {
    countryCode: "MC",
    isoAlpha3: "MCO",
    fipsCode: "MN",
    isoNumeric: 492,
    currencyCode: "EUR",
    languages: ["fr-MC", "en", "it"],
    postalCodeFormat: "#####",
    callingCode: "+377",
    timezones: ["Europe/Monaco"],
  },
  MD: {
    countryCode: "MD",
    isoAlpha3: "MDA",
    fipsCode: "MD",
    isoNumeric: 498,
    currencyCode: "MDL",
    languages: ["ro", "ru", "gag", "tr"],
    postalCodeFormat: "MD-####",
    callingCode: "+373",
    timezones: ["Europe/Chisinau"],
  },
  ME: {
    countryCode: "ME",
    isoAlpha3: "MNE",
    fipsCode: "MJ",
    isoNumeric: 499,
    currencyCode: "EUR",
    languages: ["sr", "hu", "bs", "sq", "hr", "rom"],
    postalCodeFormat: "#####",
    callingCode: "+382",
    timezones: ["Europe/Podgorica"],
  },
  MF: {
    countryCode: "MF",
    isoAlpha3: "MAF",
    fipsCode: "RN",
    isoNumeric: 663,
    currencyCode: "EUR",
    languages: ["fr"],
    postalCodeFormat: "#####",
    callingCode: "+590",
    timezones: ["America/Marigot"],
  },
  MG: {
    countryCode: "MG",
    isoAlpha3: "MDG",
    fipsCode: "MA",
    isoNumeric: 450,
    currencyCode: "MGA",
    languages: ["fr-MG", "mg"],
    postalCodeFormat: "###",
    callingCode: "+261",
    timezones: ["Indian/Antananarivo"],
  },
  MH: {
    countryCode: "MH",
    isoAlpha3: "MHL",
    fipsCode: "RM",
    isoNumeric: 584,
    currencyCode: "USD",
    languages: ["mh", "en-MH"],
    postalCodeFormat: "#####-####",
    callingCode: "+692",
    timezones: ["Pacific/Majuro", "Pacific/Kwajalein"],
  },
  MK: {
    countryCode: "MK",
    isoAlpha3: "MKD",
    fipsCode: "MK",
    isoNumeric: 807,
    currencyCode: "MKD",
    languages: ["mk", "sq", "tr", "rmm", "sr"],
    postalCodeFormat: "####",
    callingCode: "+389",
    timezones: ["Europe/Skopje"],
  },
  ML: {
    countryCode: "ML",
    isoAlpha3: "MLI",
    fipsCode: "ML",
    isoNumeric: 466,
    currencyCode: "XOF",
    languages: ["fr-ML", "bm"],
    postalCodeFormat: null,
    callingCode: "+223",
    timezones: ["Africa/Bamako"],
  },
  MM: {
    countryCode: "MM",
    isoAlpha3: "MMR",
    fipsCode: "BM",
    isoNumeric: 104,
    currencyCode: "MMK",
    languages: ["my"],
    postalCodeFormat: "#####",
    callingCode: "+95",
    timezones: ["Asia/Rangoon"],
  },
  MN: {
    countryCode: "MN",
    isoAlpha3: "MNG",
    fipsCode: "MG",
    isoNumeric: 496,
    currencyCode: "MNT",
    languages: ["mn", "ru"],
    postalCodeFormat: "######",
    callingCode: "+976",
    timezones: ["Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"],
  },
  MO: {
    countryCode: "MO",
    isoAlpha3: "MAC",
    fipsCode: "MC",
    isoNumeric: 446,
    currencyCode: "MOP",
    languages: ["zh", "zh-MO", "pt"],
    postalCodeFormat: null,
    callingCode: "+853",
    timezones: ["Asia/Macau"],
  },
  MP: {
    countryCode: "MP",
    isoAlpha3: "MNP",
    fipsCode: "CQ",
    isoNumeric: 580,
    currencyCode: "USD",
    languages: ["fil", "tl", "zh", "ch-MP", "en-MP"],
    postalCodeFormat: "#####",
    callingCode: "+1670",
    timezones: ["Pacific/Saipan"],
  },
  MQ: {
    countryCode: "MQ",
    isoAlpha3: "MTQ",
    fipsCode: "MB",
    isoNumeric: 474,
    currencyCode: "EUR",
    languages: ["fr-MQ"],
    postalCodeFormat: "#####",
    callingCode: "+596",
    timezones: ["America/Martinique"],
  },
  MR: {
    countryCode: "MR",
    isoAlpha3: "MRT",
    fipsCode: "MR",
    isoNumeric: 478,
    currencyCode: "MRU",
    languages: ["ar-MR", "fuc", "snk", "fr", "mey", "wo"],
    postalCodeFormat: null,
    callingCode: "+222",
    timezones: ["Africa/Nouakchott"],
  },
  MS: {
    countryCode: "MS",
    isoAlpha3: "MSR",
    fipsCode: "MH",
    isoNumeric: 500,
    currencyCode: "XCD",
    languages: ["en-MS"],
    postalCodeFormat: null,
    callingCode: "+1664",
    timezones: ["America/Montserrat"],
  },
  MT: {
    countryCode: "MT",
    isoAlpha3: "MLT",
    fipsCode: "MT",
    isoNumeric: 470,
    currencyCode: "EUR",
    languages: ["mt", "en-MT"],
    postalCodeFormat: "@@@ ####",
    callingCode: "+356",
    timezones: ["Europe/Malta"],
  },
  MU: {
    countryCode: "MU",
    isoAlpha3: "MUS",
    fipsCode: "MP",
    isoNumeric: 480,
    currencyCode: "MUR",
    languages: ["en-MU", "bho", "fr"],
    postalCodeFormat: null,
    callingCode: "+230",
    timezones: ["Indian/Mauritius"],
  },
  MV: {
    countryCode: "MV",
    isoAlpha3: "MDV",
    fipsCode: "MV",
    isoNumeric: 462,
    currencyCode: "MVR",
    languages: ["dv", "en"],
    postalCodeFormat: "#####",
    callingCode: "+960",
    timezones: ["Indian/Maldives"],
  },
  MW: {
    countryCode: "MW",
    isoAlpha3: "MWI",
    fipsCode: "MI",
    isoNumeric: 454,
    currencyCode: "MWK",
    languages: ["ny", "yao", "tum", "swk"],
    postalCodeFormat: "######",
    callingCode: "+265",
    timezones: ["Africa/Blantyre"],
  },
  MX: {
    countryCode: "MX",
    isoAlpha3: "MEX",
    fipsCode: "MX",
    isoNumeric: 484,
    currencyCode: "MXN",
    languages: ["es-MX"],
    postalCodeFormat: "#####",
    callingCode: "+52",
    timezones: [
      "America/Mexico_City",
      "America/Cancun",
      "America/Merida",
      "America/Monterrey",
      "America/Matamoros",
      "America/Mazatlan",
      "America/Chihuahua",
      "America/Ojinaga",
      "America/Hermosillo",
      "America/Tijuana",
      "America/Bahia_Banderas",
    ],
  },
  MY: {
    countryCode: "MY",
    isoAlpha3: "MYS",
    fipsCode: "MY",
    isoNumeric: 458,
    currencyCode: "MYR",
    languages: ["ms-MY", "en", "zh", "ta", "te", "ml", "pa", "th"],
    postalCodeFormat: "#####",
    callingCode: "+60",
    timezones: ["Asia/Kuala_Lumpur", "Asia/Kuching"],
  },
  MZ: {
    countryCode: "MZ",
    isoAlpha3: "MOZ",
    fipsCode: "MZ",
    isoNumeric: 508,
    currencyCode: "MZN",
    languages: ["pt-MZ", "vmw"],
    postalCodeFormat: "####",
    callingCode: "+258",
    timezones: ["Africa/Maputo"],
  },
  NA: {
    countryCode: "NA",
    isoAlpha3: "NAM",
    fipsCode: "WA",
    isoNumeric: 516,
    currencyCode: "NAD",
    languages: ["en-NA", "af", "de", "hz", "naq"],
    postalCodeFormat: null,
    callingCode: "+264",
    timezones: ["Africa/Windhoek"],
  },
  NC: {
    countryCode: "NC",
    isoAlpha3: "NCL",
    fipsCode: "NC",
    isoNumeric: 540,
    currencyCode: "XPF",
    languages: ["fr-NC"],
    postalCodeFormat: "#####",
    callingCode: "+687",
    timezones: ["Pacific/Noumea"],
  },
  NE: {
    countryCode: "NE",
    isoAlpha3: "NER",
    fipsCode: "NG",
    isoNumeric: 562,
    currencyCode: "XOF",
    languages: ["fr-NE", "ha", "kr", "dje"],
    postalCodeFormat: "####",
    callingCode: "+227",
    timezones: ["Africa/Niamey"],
  },
  NF: {
    countryCode: "NF",
    isoAlpha3: "NFK",
    fipsCode: "NF",
    isoNumeric: 574,
    currencyCode: "AUD",
    languages: ["en-NF"],
    postalCodeFormat: "####",
    callingCode: "+672",
    timezones: ["Pacific/Norfolk"],
  },
  NG: {
    countryCode: "NG",
    isoAlpha3: "NGA",
    fipsCode: "NI",
    isoNumeric: 566,
    currencyCode: "NGN",
    languages: ["en-NG", "ha", "yo", "ig", "ff"],
    postalCodeFormat: "######",
    callingCode: "+234",
    timezones: ["Africa/Lagos"],
  },
  NI: {
    countryCode: "NI",
    isoAlpha3: "NIC",
    fipsCode: "NU",
    isoNumeric: 558,
    currencyCode: "NIO",
    languages: ["es-NI", "en"],
    postalCodeFormat: "###-###-#",
    callingCode: "+505",
    timezones: ["America/Managua"],
  },
  NL: {
    countryCode: "NL",
    isoAlpha3: "NLD",
    fipsCode: "NL",
    isoNumeric: 528,
    currencyCode: "EUR",
    languages: ["nl-NL", "fy-NL"],
    postalCodeFormat: "#### @@",
    callingCode: "+31",
    timezones: ["Europe/Amsterdam"],
  },
  NO: {
    countryCode: "NO",
    isoAlpha3: "NOR",
    fipsCode: "NO",
    isoNumeric: 578,
    currencyCode: "NOK",
    languages: ["no", "nb", "nn", "se", "fi"],
    postalCodeFormat: "####",
    callingCode: "+47",
    timezones: ["Europe/Oslo"],
  },
  NP: {
    countryCode: "NP",
    isoAlpha3: "NPL",
    fipsCode: "NP",
    isoNumeric: 524,
    currencyCode: "NPR",
    languages: ["ne", "en"],
    postalCodeFormat: "#####",
    callingCode: "+977",
    timezones: ["Asia/Kathmandu"],
  },
  NR: {
    countryCode: "NR",
    isoAlpha3: "NRU",
    fipsCode: "NR",
    isoNumeric: 520,
    currencyCode: "AUD",
    languages: ["na", "en-NR"],
    postalCodeFormat: null,
    callingCode: "+674",
    timezones: ["Pacific/Nauru"],
  },
  NU: {
    countryCode: "NU",
    isoAlpha3: "NIU",
    fipsCode: "NE",
    isoNumeric: 570,
    currencyCode: "NZD",
    languages: ["niu", "en-NU"],
    postalCodeFormat: null,
    callingCode: "+683",
    timezones: ["Pacific/Niue"],
  },
  NZ: {
    countryCode: "NZ",
    isoAlpha3: "NZL",
    fipsCode: "NZ",
    isoNumeric: 554,
    currencyCode: "NZD",
    languages: ["en-NZ", "mi"],
    postalCodeFormat: "####",
    callingCode: "+64",
    timezones: ["Pacific/Auckland", "Pacific/Chatham"],
  },
  OM: {
    countryCode: "OM",
    isoAlpha3: "OMN",
    fipsCode: "MU",
    isoNumeric: 512,
    currencyCode: "OMR",
    languages: ["ar-OM", "en", "bal", "ur"],
    postalCodeFormat: "###",
    callingCode: "+968",
    timezones: ["Asia/Muscat"],
  },
  PA: {
    countryCode: "PA",
    isoAlpha3: "PAN",
    fipsCode: "PM",
    isoNumeric: 591,
    currencyCode: "PAB",
    languages: ["es-PA", "en"],
    postalCodeFormat: null,
    callingCode: "+507",
    timezones: ["America/Panama"],
  },
  PE: {
    countryCode: "PE",
    isoAlpha3: "PER",
    fipsCode: "PE",
    isoNumeric: 604,
    currencyCode: "PEN",
    languages: ["es-PE", "qu", "ay"],
    postalCodeFormat: "#####",
    callingCode: "+51",
    timezones: ["America/Lima"],
  },
  PF: {
    countryCode: "PF",
    isoAlpha3: "PYF",
    fipsCode: "FP",
    isoNumeric: 258,
    currencyCode: "XPF",
    languages: ["fr-PF", "ty"],
    postalCodeFormat: "#####",
    callingCode: "+689",
    timezones: ["Pacific/Tahiti", "Pacific/Marquesas", "Pacific/Gambier"],
  },
  PG: {
    countryCode: "PG",
    isoAlpha3: "PNG",
    fipsCode: "PP",
    isoNumeric: 598,
    currencyCode: "PGK",
    languages: ["en-PG", "ho", "meu", "tpi"],
    postalCodeFormat: "###",
    callingCode: "+675",
    timezones: ["Pacific/Port_Moresby", "Pacific/Bougainville"],
  },
  PH: {
    countryCode: "PH",
    isoAlpha3: "PHL",
    fipsCode: "RP",
    isoNumeric: 608,
    currencyCode: "PHP",
    languages: [
      "tl",
      "en-PH",
      "fil",
      "ceb",
      "tgl",
      "ilo",
      "hil",
      "war",
      "pam",
      "bik",
      "bcl",
      "pag",
      "mrw",
      "tsg",
      "mdh",
      "cbk",
      "krj",
      "sgd",
      "msb",
      "akl",
      "ibg",
      "yka",
      "mta",
      "abx",
    ],
    postalCodeFormat: "####",
    callingCode: "+63",
    timezones: ["Asia/Manila"],
  },
  PK: {
    countryCode: "PK",
    isoAlpha3: "PAK",
    fipsCode: "PK",
    isoNumeric: 586,
    currencyCode: "PKR",
    languages: ["ur-PK", "en-PK", "pa", "sd", "ps", "brh"],
    postalCodeFormat: "#####",
    callingCode: "+92",
    timezones: ["Asia/Karachi"],
  },
  PL: {
    countryCode: "PL",
    isoAlpha3: "POL",
    fipsCode: "PL",
    isoNumeric: 616,
    currencyCode: "PLN",
    languages: ["pl"],
    postalCodeFormat: "##-###",
    callingCode: "+48",
    timezones: ["Europe/Warsaw"],
  },
  PM: {
    countryCode: "PM",
    isoAlpha3: "SPM",
    fipsCode: "SB",
    isoNumeric: 666,
    currencyCode: "EUR",
    languages: ["fr-PM"],
    postalCodeFormat: "#####",
    callingCode: "+508",
    timezones: ["America/Miquelon"],
  },
  PN: {
    countryCode: "PN",
    isoAlpha3: "PCN",
    fipsCode: "PC",
    isoNumeric: 612,
    currencyCode: "NZD",
    languages: ["en-PN"],
    postalCodeFormat: null,
    callingCode: "+872",
    timezones: ["Pacific/Pitcairn"],
  },
  PR: {
    countryCode: "PR",
    isoAlpha3: "PRI",
    fipsCode: "RQ",
    isoNumeric: 630,
    currencyCode: "USD",
    languages: ["en-PR", "es-PR"],
    postalCodeFormat: "#####-####",
    callingCode: "+1939",
    timezones: ["America/Puerto_Rico"],
  },
  PS: {
    countryCode: "PS",
    isoAlpha3: "PSE",
    fipsCode: "WE",
    isoNumeric: 275,
    currencyCode: "ILS",
    languages: ["ar-PS"],
    postalCodeFormat: null,
    callingCode: "+970",
    timezones: ["Asia/Gaza", "Asia/Hebron"],
  },
  PT: {
    countryCode: "PT",
    isoAlpha3: "PRT",
    fipsCode: "PO",
    isoNumeric: 620,
    currencyCode: "EUR",
    languages: ["pt-PT", "mwl"],
    postalCodeFormat: "####-###",
    callingCode: "+351",
    timezones: ["Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"],
  },
  PW: {
    countryCode: "PW",
    isoAlpha3: "PLW",
    fipsCode: "PS",
    isoNumeric: 585,
    currencyCode: "USD",
    languages: ["pau", "sov", "en-PW", "tox", "ja", "fil", "zh"],
    postalCodeFormat: "96940",
    callingCode: "+680",
    timezones: ["Pacific/Palau"],
  },
  PY: {
    countryCode: "PY",
    isoAlpha3: "PRY",
    fipsCode: "PA",
    isoNumeric: 600,
    currencyCode: "PYG",
    languages: ["es-PY", "gn"],
    postalCodeFormat: "####",
    callingCode: "+595",
    timezones: ["America/Asuncion"],
  },
  QA: {
    countryCode: "QA",
    isoAlpha3: "QAT",
    fipsCode: "QA",
    isoNumeric: 634,
    currencyCode: "QAR",
    languages: ["ar-QA", "es"],
    postalCodeFormat: null,
    callingCode: "+974",
    timezones: ["Asia/Qatar"],
  },
  RE: {
    countryCode: "RE",
    isoAlpha3: "REU",
    fipsCode: "RE",
    isoNumeric: 638,
    currencyCode: "EUR",
    languages: ["fr-RE"],
    postalCodeFormat: "#####",
    callingCode: "+262",
    timezones: ["Indian/Reunion"],
  },
  RO: {
    countryCode: "RO",
    isoAlpha3: "ROU",
    fipsCode: "RO",
    isoNumeric: 642,
    currencyCode: "RON",
    languages: ["ro", "hu", "rom"],
    postalCodeFormat: "######",
    callingCode: "+40",
    timezones: ["Europe/Bucharest"],
  },
  RS: {
    countryCode: "RS",
    isoAlpha3: "SRB",
    fipsCode: "RI",
    isoNumeric: 688,
    currencyCode: "RSD",
    languages: ["sr", "hu", "bs", "rom"],
    postalCodeFormat: "######",
    callingCode: "+381",
    timezones: ["Europe/Belgrade"],
  },
  RU: {
    countryCode: "RU",
    isoAlpha3: "RUS",
    fipsCode: "RS",
    isoNumeric: 643,
    currencyCode: "RUB",
    languages: [
      "ru",
      "tt",
      "xal",
      "cau",
      "ady",
      "kv",
      "ce",
      "tyv",
      "cv",
      "udm",
      "tut",
      "mns",
      "bua",
      "myv",
      "mdf",
      "chm",
      "ba",
      "inh",
      "tut",
      "kbd",
      "krc",
      "av",
      "sah",
      "nog",
    ],
    postalCodeFormat: "######",
    callingCode: "+7",
    timezones: [
      "Europe/Kaliningrad",
      "Europe/Moscow",
      "Europe/Simferopol",
      "Europe/Volgograd",
      "Europe/Kirov",
      "Europe/Astrakhan",
      "Europe/Samara",
      "Europe/Ulyanovsk",
      "Asia/Yekaterinburg",
      "Asia/Omsk",
      "Asia/Novosibirsk",
      "Asia/Barnaul",
      "Asia/Tomsk",
      "Asia/Novokuznetsk",
      "Asia/Krasnoyarsk",
      "Asia/Irkutsk",
      "Asia/Chita",
      "Asia/Yakutsk",
      "Asia/Khandyga",
      "Asia/Vladivostok",
      "Asia/Ust-Nera",
      "Asia/Magadan",
      "Asia/Sakhalin",
      "Asia/Srednekolymsk",
      "Asia/Kamchatka",
      "Asia/Anadyr",
    ],
  },
  RW: {
    countryCode: "RW",
    isoAlpha3: "RWA",
    fipsCode: "RW",
    isoNumeric: 646,
    currencyCode: "RWF",
    languages: ["rw", "en-RW", "fr-RW", "sw"],
    postalCodeFormat: null,
    callingCode: "+250",
    timezones: ["Africa/Kigali"],
  },
  SA: {
    countryCode: "SA",
    isoAlpha3: "SAU",
    fipsCode: "SA",
    isoNumeric: 682,
    currencyCode: "SAR",
    languages: ["ar-SA"],
    postalCodeFormat: "#####",
    callingCode: "+966",
    timezones: ["Asia/Riyadh"],
  },
  SB: {
    countryCode: "SB",
    isoAlpha3: "SLB",
    fipsCode: "BP",
    isoNumeric: 90,
    currencyCode: "SBD",
    languages: ["en-SB", "tpi"],
    postalCodeFormat: null,
    callingCode: "+677",
    timezones: ["Pacific/Guadalcanal"],
  },
  SC: {
    countryCode: "SC",
    isoAlpha3: "SYC",
    fipsCode: "SE",
    isoNumeric: 690,
    currencyCode: "SCR",
    languages: ["en-SC", "fr-SC"],
    postalCodeFormat: null,
    callingCode: "+248",
    timezones: ["Indian/Mahe"],
  },
  SD: {
    countryCode: "SD",
    isoAlpha3: "SDN",
    fipsCode: "SU",
    isoNumeric: 729,
    currencyCode: "SDG",
    languages: ["ar-SD", "en", "fia"],
    postalCodeFormat: "#####",
    callingCode: "+249",
    timezones: ["Africa/Khartoum"],
  },
  SE: {
    countryCode: "SE",
    isoAlpha3: "SWE",
    fipsCode: "SW",
    isoNumeric: 752,
    currencyCode: "SEK",
    languages: ["sv-SE", "se", "sma", "fi-SE"],
    postalCodeFormat: "### ##",
    callingCode: "+46",
    timezones: ["Europe/Stockholm"],
  },
  SG: {
    countryCode: "SG",
    isoAlpha3: "SGP",
    fipsCode: "SN",
    isoNumeric: 702,
    currencyCode: "SGD",
    languages: ["cmn", "en-SG", "ms-SG", "ta-SG", "zh-SG"],
    postalCodeFormat: "######",
    callingCode: "+65",
    timezones: ["Asia/Singapore"],
  },
  SH: {
    countryCode: "SH",
    isoAlpha3: "SHN",
    fipsCode: "SH",
    isoNumeric: 654,
    currencyCode: "SHP",
    languages: ["en-SH"],
    postalCodeFormat: "STHL 1ZZ",
    callingCode: "+290",
    timezones: ["Atlantic/St_Helena"],
  },
  SI: {
    countryCode: "SI",
    isoAlpha3: "SVN",
    fipsCode: "SI",
    isoNumeric: 705,
    currencyCode: "EUR",
    languages: ["sl", "sh"],
    postalCodeFormat: "####",
    callingCode: "+386",
    timezones: ["Europe/Ljubljana"],
  },
  SJ: {
    countryCode: "SJ",
    isoAlpha3: "SJM",
    fipsCode: "SV",
    isoNumeric: 744,
    currencyCode: "NOK",
    languages: ["no", "ru"],
    postalCodeFormat: "####",
    callingCode: "+47",
    timezones: ["Arctic/Longyearbyen"],
  },
  SK: {
    countryCode: "SK",
    isoAlpha3: "SVK",
    fipsCode: "LO",
    isoNumeric: 703,
    currencyCode: "EUR",
    languages: ["sk", "hu"],
    postalCodeFormat: "### ##",
    callingCode: "+421",
    timezones: ["Europe/Bratislava"],
  },
  SL: {
    countryCode: "SL",
    isoAlpha3: "SLE",
    fipsCode: "SL",
    isoNumeric: 694,
    currencyCode: "SLL",
    languages: ["en-SL", "men", "tem"],
    postalCodeFormat: null,
    callingCode: "+232",
    timezones: ["Africa/Freetown"],
  },
  SM: {
    countryCode: "SM",
    isoAlpha3: "SMR",
    fipsCode: "SM",
    isoNumeric: 674,
    currencyCode: "EUR",
    languages: ["it-SM"],
    postalCodeFormat: "4789#",
    callingCode: "+378",
    timezones: ["Europe/San_Marino"],
  },
  SN: {
    countryCode: "SN",
    isoAlpha3: "SEN",
    fipsCode: "SG",
    isoNumeric: 686,
    currencyCode: "XOF",
    languages: ["fr-SN", "wo", "fuc", "mnk"],
    postalCodeFormat: "#####",
    callingCode: "+221",
    timezones: ["Africa/Dakar"],
  },
  SO: {
    countryCode: "SO",
    isoAlpha3: "SOM",
    fipsCode: "SO",
    isoNumeric: 706,
    currencyCode: "SOS",
    languages: ["so-SO", "ar-SO", "it", "en-SO"],
    postalCodeFormat: "@@  #####",
    callingCode: "+252",
    timezones: ["Africa/Mogadishu"],
  },
  SR: {
    countryCode: "SR",
    isoAlpha3: "SUR",
    fipsCode: "NS",
    isoNumeric: 740,
    currencyCode: "SRD",
    languages: ["nl-SR", "en", "srn", "hns", "jv"],
    postalCodeFormat: null,
    callingCode: "+597",
    timezones: ["America/Paramaribo"],
  },
  SS: {
    countryCode: "SS",
    isoAlpha3: "SSD",
    fipsCode: "OD",
    isoNumeric: 728,
    currencyCode: "SSP",
    languages: ["en"],
    postalCodeFormat: null,
    callingCode: "+211",
    timezones: ["Africa/Juba"],
  },
  ST: {
    countryCode: "ST",
    isoAlpha3: "STP",
    fipsCode: "TP",
    isoNumeric: 678,
    currencyCode: "STN",
    languages: ["pt-ST"],
    postalCodeFormat: null,
    callingCode: "+239",
    timezones: ["Africa/Sao_Tome"],
  },
  SV: {
    countryCode: "SV",
    isoAlpha3: "SLV",
    fipsCode: "ES",
    isoNumeric: 222,
    currencyCode: "USD",
    languages: ["es-SV"],
    postalCodeFormat: "CP ####",
    callingCode: "+503",
    timezones: ["America/El_Salvador"],
  },
  SX: {
    countryCode: "SX",
    isoAlpha3: "SXM",
    fipsCode: "NN",
    isoNumeric: 534,
    currencyCode: "ANG",
    languages: ["nl", "en"],
    postalCodeFormat: null,
    callingCode: "+599",
    timezones: ["America/Lower_Princes"],
  },
  SY: {
    countryCode: "SY",
    isoAlpha3: "SYR",
    fipsCode: "SY",
    isoNumeric: 760,
    currencyCode: "SYP",
    languages: ["ar-SY", "ku", "hy", "arc", "fr", "en"],
    postalCodeFormat: null,
    callingCode: "+963",
    timezones: ["Asia/Damascus"],
  },
  SZ: {
    countryCode: "SZ",
    isoAlpha3: "SWZ",
    fipsCode: "WZ",
    isoNumeric: 748,
    currencyCode: "SZL",
    languages: ["en-SZ", "ss-SZ"],
    postalCodeFormat: "@###",
    callingCode: "+268",
    timezones: ["Africa/Mbabane"],
  },
  TC: {
    countryCode: "TC",
    isoAlpha3: "TCA",
    fipsCode: "TK",
    isoNumeric: 796,
    currencyCode: "USD",
    languages: ["en-TC"],
    postalCodeFormat: "TKCA 1ZZ",
    callingCode: "+1649",
    timezones: ["America/Grand_Turk"],
  },
  TD: {
    countryCode: "TD",
    isoAlpha3: "TCD",
    fipsCode: "CD",
    isoNumeric: 148,
    currencyCode: "XAF",
    languages: ["fr-TD", "ar-TD", "sre"],
    postalCodeFormat: null,
    callingCode: "+235",
    timezones: ["Africa/Ndjamena"],
  },
  TF: {
    countryCode: "TF",
    isoAlpha3: "ATF",
    fipsCode: "FS",
    isoNumeric: 260,
    currencyCode: "EUR",
    languages: ["fr"],
    postalCodeFormat: null,
    callingCode: "+262",
    timezones: ["Indian/Kerguelen"],
  },
  TG: {
    countryCode: "TG",
    isoAlpha3: "TGO",
    fipsCode: "TO",
    isoNumeric: 768,
    currencyCode: "XOF",
    languages: ["fr-TG", "ee", "hna", "kbp", "dag", "ha"],
    postalCodeFormat: null,
    callingCode: "+228",
    timezones: ["Africa/Lome"],
  },
  TH: {
    countryCode: "TH",
    isoAlpha3: "THA",
    fipsCode: "TH",
    isoNumeric: 764,
    currencyCode: "THB",
    languages: ["th", "en"],
    postalCodeFormat: "#####",
    callingCode: "+66",
    timezones: ["Asia/Bangkok"],
  },
  TJ: {
    countryCode: "TJ",
    isoAlpha3: "TJK",
    fipsCode: "TI",
    isoNumeric: 762,
    currencyCode: "TJS",
    languages: ["tg", "ru"],
    postalCodeFormat: "######",
    callingCode: "+992",
    timezones: ["Asia/Dushanbe"],
  },
  TK: {
    countryCode: "TK",
    isoAlpha3: "TKL",
    fipsCode: "TL",
    isoNumeric: 772,
    currencyCode: "NZD",
    languages: ["tkl", "en-TK"],
    postalCodeFormat: null,
    callingCode: "+690",
    timezones: ["Pacific/Fakaofo"],
  },
  TL: {
    countryCode: "TL",
    isoAlpha3: "TLS",
    fipsCode: "TT",
    isoNumeric: 626,
    currencyCode: "USD",
    languages: ["tet", "pt-TL", "id", "en"],
    postalCodeFormat: null,
    callingCode: "+670",
    timezones: ["Asia/Dili"],
  },
  TM: {
    countryCode: "TM",
    isoAlpha3: "TKM",
    fipsCode: "TX",
    isoNumeric: 795,
    currencyCode: "TMT",
    languages: ["tk", "ru", "uz"],
    postalCodeFormat: "######",
    callingCode: "+993",
    timezones: ["Asia/Ashgabat"],
  },
  TN: {
    countryCode: "TN",
    isoAlpha3: "TUN",
    fipsCode: "TS",
    isoNumeric: 788,
    currencyCode: "TND",
    languages: ["ar-TN", "fr"],
    postalCodeFormat: "####",
    callingCode: "+216",
    timezones: ["Africa/Tunis"],
  },
  TO: {
    countryCode: "TO",
    isoAlpha3: "TON",
    fipsCode: "TN",
    isoNumeric: 776,
    currencyCode: "TOP",
    languages: ["to", "en-TO"],
    postalCodeFormat: null,
    callingCode: "+676",
    timezones: ["Pacific/Tongatapu"],
  },
  TR: {
    countryCode: "TR",
    isoAlpha3: "TUR",
    fipsCode: "TU",
    isoNumeric: 792,
    currencyCode: "TRY",
    languages: ["tr-TR", "ku", "diq", "az", "av"],
    postalCodeFormat: "#####",
    callingCode: "+90",
    timezones: ["Europe/Istanbul"],
  },
  TT: {
    countryCode: "TT",
    isoAlpha3: "TTO",
    fipsCode: "TD",
    isoNumeric: 780,
    currencyCode: "TTD",
    languages: ["en-TT", "hns", "fr", "es", "zh"],
    postalCodeFormat: null,
    callingCode: "+1868",
    timezones: ["America/Port_of_Spain"],
  },
  TV: {
    countryCode: "TV",
    isoAlpha3: "TUV",
    fipsCode: "TV",
    isoNumeric: 798,
    currencyCode: "AUD",
    languages: ["tvl", "en", "sm", "gil"],
    postalCodeFormat: null,
    callingCode: "+688",
    timezones: ["Pacific/Funafuti"],
  },
  TW: {
    countryCode: "TW",
    isoAlpha3: "TWN",
    fipsCode: "TW",
    isoNumeric: 158,
    currencyCode: "TWD",
    languages: ["zh-TW", "zh", "nan", "hak"],
    postalCodeFormat: "#####",
    callingCode: "+886",
    timezones: ["Asia/Taipei"],
  },
  TZ: {
    countryCode: "TZ",
    isoAlpha3: "TZA",
    fipsCode: "TZ",
    isoNumeric: 834,
    currencyCode: "TZS",
    languages: ["sw-TZ", "en", "ar"],
    postalCodeFormat: null,
    callingCode: "+255",
    timezones: ["Africa/Dar_es_Salaam"],
  },
  UA: {
    countryCode: "UA",
    isoAlpha3: "UKR",
    fipsCode: "UP",
    isoNumeric: 804,
    currencyCode: "UAH",
    languages: ["uk", "ru-UA", "rom", "pl", "hu"],
    postalCodeFormat: "#####",
    callingCode: "+380",
    timezones: ["Europe/Kiev", "Europe/Uzhgorod", "Europe/Zaporozhye"],
  },
  UG: {
    countryCode: "UG",
    isoAlpha3: "UGA",
    fipsCode: "UG",
    isoNumeric: 800,
    currencyCode: "UGX",
    languages: ["en-UG", "lg", "sw", "ar"],
    postalCodeFormat: null,
    callingCode: "+256",
    timezones: ["Africa/Kampala"],
  },
  UM: {
    countryCode: "UM",
    isoAlpha3: "UMI",
    fipsCode: null,
    isoNumeric: 581,
    currencyCode: "USD",
    languages: ["en-UM"],
    postalCodeFormat: null,
    callingCode: "+246",
    timezones: ["Pacific/Johnston", "Pacific/Midway", "Pacific/Wake"],
  },
  US: {
    countryCode: "US",
    isoAlpha3: "USA",
    fipsCode: "US",
    isoNumeric: 840,
    currencyCode: "USD",
    languages: ["en-US", "es-US", "haw", "fr"],
    postalCodeFormat: "#####-####",
    callingCode: "+1",
    timezones: [
      "America/New_York",
      "America/Detroit",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/Indiana/Indianapolis",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Vevay",
      "America/Chicago",
      "America/Indiana/Tell_City",
      "America/Indiana/Knox",
      "America/Menominee",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "America/North_Dakota/Beulah",
      "America/Denver",
      "America/Boise",
      "America/Phoenix",
      "America/Los_Angeles",
      "America/Anchorage",
      "America/Juneau",
      "America/Sitka",
      "America/Metlakatla",
      "America/Yakutat",
      "America/Nome",
      "America/Adak",
      "Pacific/Honolulu",
    ],
  },
  UY: {
    countryCode: "UY",
    isoAlpha3: "URY",
    fipsCode: "UY",
    isoNumeric: 858,
    currencyCode: "UYU",
    languages: ["es-UY"],
    postalCodeFormat: "#####",
    callingCode: "+598",
    timezones: ["America/Montevideo"],
  },
  UZ: {
    countryCode: "UZ",
    isoAlpha3: "UZB",
    fipsCode: "UZ",
    isoNumeric: 860,
    currencyCode: "UZS",
    languages: ["uz", "ru", "tg"],
    postalCodeFormat: "######",
    callingCode: "+998",
    timezones: ["Asia/Samarkand", "Asia/Tashkent"],
  },
  VA: {
    countryCode: "VA",
    isoAlpha3: "VAT",
    fipsCode: "VT",
    isoNumeric: 336,
    currencyCode: "EUR",
    languages: ["la", "it", "fr"],
    postalCodeFormat: "#####",
    callingCode: "+379",
    timezones: ["Europe/Vatican"],
  },
  VC: {
    countryCode: "VC",
    isoAlpha3: "VCT",
    fipsCode: "VC",
    isoNumeric: 670,
    currencyCode: "XCD",
    languages: ["en-VC", "fr"],
    postalCodeFormat: null,
    callingCode: "+1784",
    timezones: ["America/St_Vincent"],
  },
  VE: {
    countryCode: "VE",
    isoAlpha3: "VEN",
    fipsCode: "VE",
    isoNumeric: 862,
    currencyCode: "VES",
    languages: ["es-VE"],
    postalCodeFormat: "####",
    callingCode: "+58",
    timezones: ["America/Caracas"],
  },
  VG: {
    countryCode: "VG",
    isoAlpha3: "VGB",
    fipsCode: "VI",
    isoNumeric: 92,
    currencyCode: "USD",
    languages: ["en-VG"],
    postalCodeFormat: null,
    callingCode: "+1284",
    timezones: ["America/Tortola"],
  },
  VI: {
    countryCode: "VI",
    isoAlpha3: "VIR",
    fipsCode: "VQ",
    isoNumeric: 850,
    currencyCode: "USD",
    languages: ["en-VI"],
    postalCodeFormat: "#####-####",
    callingCode: "+1340",
    timezones: ["America/St_Thomas"],
  },
  VN: {
    countryCode: "VN",
    isoAlpha3: "VNM",
    fipsCode: "VM",
    isoNumeric: 704,
    currencyCode: "VND",
    languages: ["vi", "en", "fr", "zh", "km"],
    postalCodeFormat: "######",
    callingCode: "+84",
    timezones: ["Asia/Ho_Chi_Minh"],
  },
  VU: {
    countryCode: "VU",
    isoAlpha3: "VUT",
    fipsCode: "NH",
    isoNumeric: 548,
    currencyCode: "VUV",
    languages: ["bi", "en-VU", "fr-VU"],
    postalCodeFormat: null,
    callingCode: "+678",
    timezones: ["Pacific/Efate"],
  },
  WF: {
    countryCode: "WF",
    isoAlpha3: "WLF",
    fipsCode: "WF",
    isoNumeric: 876,
    currencyCode: "XPF",
    languages: ["wls", "fud", "fr-WF"],
    postalCodeFormat: "#####",
    callingCode: "+681",
    timezones: ["Pacific/Wallis"],
  },
  WS: {
    countryCode: "WS",
    isoAlpha3: "WSM",
    fipsCode: "WS",
    isoNumeric: 882,
    currencyCode: "WST",
    languages: ["sm", "en-WS"],
    postalCodeFormat: null,
    callingCode: "+685",
    timezones: ["Pacific/Apia"],
  },
  XK: {
    countryCode: "XK",
    isoAlpha3: "XKX",
    fipsCode: "KV",
    isoNumeric: 0,
    currencyCode: "EUR",
    languages: ["sq", "sr"],
    postalCodeFormat: null,
    callingCode: "+383",
    timezones: ["Europe/Belgrade"],
  },
  YE: {
    countryCode: "YE",
    isoAlpha3: "YEM",
    fipsCode: "YM",
    isoNumeric: 887,
    currencyCode: "YER",
    languages: ["ar-YE"],
    postalCodeFormat: null,
    callingCode: "+967",
    timezones: ["Asia/Aden"],
  },
  YT: {
    countryCode: "YT",
    isoAlpha3: "MYT",
    fipsCode: "MF",
    isoNumeric: 175,
    currencyCode: "EUR",
    languages: ["fr-YT"],
    postalCodeFormat: "#####",
    callingCode: "+262",
    timezones: ["Indian/Mayotte"],
  },
  ZA: {
    countryCode: "ZA",
    isoAlpha3: "ZAF",
    fipsCode: "SF",
    isoNumeric: 710,
    currencyCode: "ZAR",
    languages: [
      "zu",
      "xh",
      "af",
      "nso",
      "en-ZA",
      "tn",
      "st",
      "ts",
      "ss",
      "ve",
      "nr",
    ],
    postalCodeFormat: "####",
    callingCode: "+27",
    timezones: ["Africa/Johannesburg"],
  },
  ZM: {
    countryCode: "ZM",
    isoAlpha3: "ZMB",
    fipsCode: "ZA",
    isoNumeric: 894,
    currencyCode: "ZMW",
    languages: ["en-ZM", "bem", "loz", "lun", "lue", "ny", "toi"],
    postalCodeFormat: "#####",
    callingCode: "+260",
    timezones: ["Africa/Lusaka"],
  },
  ZW: {
    countryCode: "ZW",
    isoAlpha3: "ZWE",
    fipsCode: "ZI",
    isoNumeric: 716,
    currencyCode: "ZWL",
    languages: ["en-ZW", "sn", "nr", "nd"],
    postalCodeFormat: null,
    callingCode: "+263",
    timezones: ["Africa/Harare"],
  },
} as const;

export type Countries = typeof COUNTRIES;
export type CountryKey = keyof Countries;
export type Country = Countries[CountryKey];

export const COUNTRY_KEYS = Object.keys(COUNTRIES) as CountryKey[];
export const COUNTRY_VALUES = Object.values(COUNTRIES) as Country[];

export const DEFAULT_COUNTRY = COUNTRIES.NL;
